name: Build & Push image (prod)

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Scaleway Container Registry
              uses: docker/login-action@v3
              with:
                  username: nologin
                  password: ${{ secrets.SCALEWAY_API_KEY }}
                  registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}

            - name: Compute tags
              id: meta
              run: |
                  SHA_TAG=${GITHUB_SHA::12}
                  echo "sha_tag=$SHA_TAG" >> $GITHUB_OUTPUT

            - name: Build & push (prod + sha)
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/scaleway_gleam:prod
                      ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/scaleway_gleam:${{ steps.meta.outputs.sha_tag }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
